export const FETCH_TRANSACTIONS = "FETCH_TRANSACTIONS";
export const FETCH_TRANSACTIONS_SUCCESS = "FETCH_TRANSACTIONS_SUCCESS";
export const FETCH_TRANSACTIONS_FAILED = "FETCH_TRANSACTIONS_FAILED";

export const AUTHENTICATE = "AUTHENTICATE";
export const AUTHENTICATE_SUCCESS = "AUTHENTICATE_SUCCESS";
export const AUTHENTICATE_FAILED = "AUTHENTICATE_FAILED";

export const GET_USER_DATA = "GET_USER_DATA";
export const GET_USER_DATA_SUCCESSED = "GET_USER_DATA_SUCCESSED";
export const GET_USER_DATA_FAILED = "GET_USER_DATA_FAILED";
